version: '3'
services:
  metasploitable1:
    image: tleemcjr/metasploitable2
    volumes:
      - ./files:/start
    networks:
      subnet1:
        ipv4_address: 172.16.10.2
      subnet2:
        ipv4_address: 172.16.20.3
    ports:
      - "8888:80"
    container_name: metasploitable1
    command: sh -c "
      /start/ms1.sh &&
      tail -f /dev/null
      "

  metasploitable2:
    image: tleemcjr/metasploitable2
    volumes:
      - ./files:/start
    networks:
      subnet2:
        ipv4_address: 172.16.20.2
    container_name: metasploitable2
    command: sh -c "
      /bin/services.sh &&
      tail -f /dev/null
      "

networks:
  subnet1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24

  subnet2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24

