version: '3'
services:
  metasploitable1:
    image: tleemcjr/metasploitable2
    networks:
      subnet1:
        ipv4_address: 172.16.1.2
      subnet2:
        ipv4_address: 172.16.2.3
    ports:
      - "21:21"
      - "8888:80"
      - "6667:6667"
    container_name: metasploitable1
    command: sh -c "
      /bin/services.sh &&
      tail -f /dev/null
      "

  metasploitable2:
    image: tleemcjr/metasploitable2
    networks:
      subnet2:
        ipv4_address: 172.16.2.2
      subnet3:
        ipv4_address: 172.16.3.3
    container_name: metasploitable2
    command: sh -c "
      /bin/services.sh &&
      tail -f /dev/null
      "

  metasploitable3:
    image: tleemcjr/metasploitable2
    networks:
      subnet3:
        ipv4_address: 172.16.3.2
    container_name: metasploitable3
    command: sh -c "
      /bin/services.sh &&
      tail -f /dev/null
      "

networks:
  subnet1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

  subnet2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24

  subnet3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.3.0/24
